export const JOBS = [
    "Account Management",
    "Accountancy",
    "Advisory / Consultancy",
    "AR/VR",
"Banking",
"Clerical / Administrative",
"Commercial",
"Cyber-Security",
"Data",
"Design / UX/UI",
"DevOps",
"Finance",
"HR / Recruitment",
"Infrastructure",
"International Expansion",
"Legal",
"Machine Learning / AI",
"Management / Non-Executive Director",
"Marketing / Growth",
"Mobile",
"Operations",
"Partnerships",
"Product",
"Sales / Business Development",
"Secretarial",
"Software Engineering",
"Strategy",
"Transformation"];
